---
deployment:
  tasks:
    - export DEPLOYPATH=/home/groupenovitec/public_html/
    - /bin/mkdir -p $DEPLOYPATH
    - /bin/cp -rf dist/* $DEPLOYPATH/
    - /bin/cp .htaccess $DEPLOYPATH/
    - /bin/echo "Déploiement terminé avec succès" > $DEPLOYPATH/deploy_status.txt
